name: Pipeline

on:
  push:
    branches:
    - main

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: npm i
    - run: npm run build
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'derekbrown.io'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist'
    - uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://derekbrown.io", "https://www.derekbrown.io"]'
        expected: '[200, 301]'
    - uses: Ilshidur/action-discord@master
      with:
        args: 'https://derekbrown.io has been deployed.'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}