name: Pipeline

on:
  push:
    branches:
    - main
    paths:
      - src/**
      - .github/**
      - astro.*

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@main

    - name: Install node packages
      run: make reset_astro

    - name: Authenticate AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Build website
      run: make build

    - name: Upload website
      run: make sync

    - name: Purge website
      run: make purge

    - name: Wait 30 seconds
      run: sleep 30

    - name: Check Site Status
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://derekbrown.io", "https://www.derekbrown.io"]'
        expected: '[200, 301]'

    - name: Send Discord Message
      uses: Ilshidur/action-discord@master
      with:
        args: 'https://derekbrown.io has been deployed.'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}