name: Pipeline

on:
  push:
    branches:
    - main

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: npm i
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
    - run: npm run build
    - run: aws s3 sync ./dist s3://derekbrown.io
    - run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST_ID }} \
        --paths '/*' \
        --no-cli-pager
    - uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://derekbrown.io", "https://www.derekbrown.io"]'
        expected: '[200, 301]'
    - uses: Ilshidur/action-discord@master
      with:
        args: 'https://derekbrown.io has been deployed.'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}